### PR TITLE
sdk 1.1.0

### PR DESCRIPTION
**Pull request by asutula**
Mostly related to `Contact`.

### CODE REVIEW

**Comment by asutula** [comment]
This one will require an update to the beta cafe

**Comment by asutula** [comment]
And this is using sdk 1.1.1 (found some bugs in the sdk during this process, had to update it)

**Comment by sanderpick** [comment]
I can update the beta machine after merge.

**Comment by asutula** [comment]
Ok merged, update it.

**Comment by sanderpick** [comment]
Beta is now running v0.1.11 of go-textile.

**Pull request merged**
