### PR TITLE
Minor updates to TERMS

### PR DESCRIPTION
**Pull request by carsonfarmer**
Some minor typos etc. Nothing crazy here, not a priority.

### CODE REVIEW

**Comment by asutula** [comment]
Just seeing what the 'update branch' button does to get this branch up to date with master. Looks like it uses a plain merge, not rebase.

**Comment by carsonfarmer** [comment]
whoah, that's kinda cool though

**Comment by andrewxhill** [comment]
is this gtg? it's assigned to yourself

**Comment by carsonfarmer** [comment]
Yup, GTG

**Comment by carsonfarmer** [comment]
updating then will merge when done

**Pull request merged**
