### PR TITLE
Node logs fix

### PR DESCRIPTION
**Pull request by asutula**
Fixes log reading offset bug, clear out in memory data when loading more log data just to avoid memory pressure crashes. I think it was probably the offset bug causing our crash, though.

### CODE REVIEW

**Comment by asutula** [comment]
Also set the log level to DEBUG for local dev builds, but ERROR for beta and release builds

**Comment by asutula** [comment]
Oh actually, would it be better to have the Fabric Beta builds be logging at DEBUG? I think we can actually do that with our .env based setup.

**Comment by asutula** [comment]
Ok now using .env `RN_RELEASE_TYPE` so local dev builds and Fabric beta builds use DEBUG, production builds ERROR.

**Comment by sanderpick** [comment]
Awesome dude. After we merge/release your mobile api for dynamic logs, we could also switch to DEBUG when you long press the logo. Could be great for remote debugging with a real user.

**Pull request merged**
