### PR TITLE
carson/mobile cookies for ios

### PR DESCRIPTION
**Pull request by carsonfarmer**

### CODE REVIEW

**Comment by carsonfarmer** [comment]
Huh, well this is an issue:
https://github.com/joeferraro/react-native-cookies/issues/84
I might have to update the lib I'm using for writing cookies. Should be easy enough...

**Comment by andrewxhill** [comment]
can we launch without this or is the a requirement for the secure calls?

**Comment by carsonfarmer** [comment]
Right now, we have https working fully. But without the cookie stuff, someone with access to localhost could have requests and get photos. 
I think if I can do a platform check from RN, we can use this lib for now. Then it’s just a matter of exposing the gateway password to RN, which I think is easy enough.

**Comment by andrewxhill** [comment]
yeah, `if (Platform.OS === 'android')` is all you want.

**Comment by carsonfarmer** [comment]
ok, this is finally good to go... works on ios. probably won't work on android given a) the https issues and b) the client-side cookie adding has not been tested properly

**Pull request merged**
