### PR TITLE
Cleans up a lot of the un-clickable buttons

### PR DESCRIPTION
**Pull request by andrewxhill**

### CODE REVIEW

**Comment by andrewxhill** [comment]
also gtg

**Comment by asutula** [comment]
What do you think about using `react-native-header-buttons`? Not sure if you've tried it out, but it worked nicely in previous versions of the app.

**Comment by andrewxhill** [comment]
ah shoot, forgot you had mentioned those before. let's get this guy in and i'll go back and replace next time around

**Comment by asutula** [comment]
Are there any changes in this branch we actually need to keep then? Or can we just close this?

**Comment by andrewxhill** [comment]
dunno, i'd say let's put it in because it makes the app more usable already... (there are non-header buttons fixed here too) and then i can replace with that follow-up work

**Comment by asutula** [comment]
I don't know about merging this because it will definitely lead to a lot of unused code, mostly styling code, sitting around once we switch to to header buttons.

**Comment by asutula** [comment]
ok, let's just be sure to actually clean up later then

**Pull request merged**
